### ISSUE TITLE
Does not work on FreeBSD

### ISSUE THREAD

**Issue by zg** [dnaeon/gerrit-freebsd#2]
Unfortunately, this doesn't appear to be working on FreeBSD 10.2.

```
# make install clean
===>   gerrit-2.5 depends on file: /usr/local/sbin/pkg - found
=> gerrit-full-2.5.war doesn't seem to exist in /usr/ports/distfiles/.
=> Attempting to fetch http://gerrit.googlecode.com/files/gerrit-full-2.5.war
fetch: http://gerrit.googlecode.com/files/gerrit-full-2.5.war: Not Found
=> Attempting to fetch http://distcache.FreeBSD.org/ports-distfiles/gerrit-full-2.5.war
fetch: http://distcache.FreeBSD.org/ports-distfiles/gerrit-full-2.5.war: Not Found
=> Couldn't fetch it - please try to retrieve this
=> port manually into /usr/ports/distfiles/ and try again.
*** Error code 1

Stop.
make: stopped in /root/gerrit-freebsd
```

It appears that the war file is not available on FreeBSD.org.

**Comment by dnaeon** [comment]
The version needs to be bumped. Can you update the version from the Makefile to the latest one of Gerrit and try again?

**Comment by zg** [comment]
How do I find out what the latest version is?

**Comment by zg** [comment]
The newest version of Gerrit is 2.13.1, but that isn't up on the distcache. I hit a 404 for `http://distcache.freebsd.org/ports-distfiles/gerrit-2.{0..20}.{0..10}.war` as well.

**Comment by dnaeon** [comment]
Just fetch the distfile manually. The port needs to be updated first, that's why it's missing from the FreeBSD distcache servers.

**Comment by zg** [comment]
Where do I put the distfile?

**Comment by zg** [comment]
Nevermind, I clearly need to focus more on the output that was given. I placed it in `/usr/ports/distfiles`.

**Comment by zg** [comment]
What happened to the efforts around getting a port with FreeBSD?

**Comment by dnaeon** [comment]
Not sure, it was long time ago. If it isn't in the ports tree already, then it wasn't merged. Interested in submitting a PR for adding it?
